name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          job: 'GitHub Actions Test'
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Test Local Action with Anchor
        id: test-action-anchor
        uses: ./
        with:
          job: 'GitHub Actions Test'
          include_job_summary_anchor: true
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Print Outputs
        id: output
        run: |
          echo "=== Without Anchor ==="
          echo "Run URL: ${{ steps.test-action.outputs.run_url }}"
          echo "Job ID: ${{ steps.test-action.outputs.job_id }}"
          echo "Job Name: ${{ steps.test-action.outputs.job_name }}"
          echo "Job URL: ${{ steps.test-action.outputs.job_url }}"
          echo "Job Summary URL: ${{ steps.test-action.outputs.job_summary_url }}"
          echo "Workflow Name: ${{ steps.test-action.outputs.workflow_name }}"
          echo ""
          echo "=== With Anchor ==="
          echo "Job Summary URL (with anchor): ${{ steps.test-action-anchor.outputs.job_summary_url }}"

      - name: Write Job Summary
        run: |
          {
            echo "# GitHub Actions Test Job Summary"
            echo ""
            echo "This is a test job summary to verify the action outputs."
            echo ""
            echo "## Action Outputs (Default - No Anchor)"
            echo ""
            echo "| Output | Value |"
            echo "|--------:|-------|"
            echo "| Run URL | ${{ steps.test-action.outputs.run_url }} |"
            echo "| Job ID | ${{ steps.test-action.outputs.job_id }} |"
            echo "| Job Name | ${{ steps.test-action.outputs.job_name }} |"
            echo "| Job URL | ${{ steps.test-action.outputs.job_url }} |"
            echo "| Job Summary URL | ${{ steps.test-action.outputs.job_summary_url }} |"
            echo "| Job Status | ${{ steps.test-action.outputs.job_status }} |"
            echo "| Workflow Name | ${{ steps.test-action.outputs.workflow_name }} |"
            echo "| Run Number | ${{ steps.test-action.outputs.run_number }} |"
            echo ""
            echo "## Action Outputs (With Anchor)"
            echo ""
            echo "| Output | Value |"
            echo "|--------:|-------|"
            echo "| Job Summary URL (with anchor) | ${{ steps.test-action-anchor.outputs.job_summary_url }} |"
            echo ""
            echo "✅ Test completed successfully!"
          } >> "$GITHUB_STEP_SUMMARY"
